apiVersion: monitoring.io/v1
kind: Stats
metadata:
  labels:
    app.kubernetes.io/name: stats-controller
    app.kubernetes.io/managed-by: kustomize
  name: stats-example
spec: {}
status:
    runningPods: 1
    deployments: 1
    daemonSets: 1
    statefulSets: 1
    replicaSets: 1
    deploymentNames:
    - nginx-ingress-controller
    daemonSetNames:
    - stats-daemonset
    statefulSetNames:
      - mysql
    replicaSetNames:
    - nginx-ingress-controller-7d9d88f7d

